In [2]:
import os
import cv2
import sys
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

current_path = os.getcwd()
print(current_path)
project_root_path = os.path.abspath(os.path.join(current_path, '..'))
print(project_root_path)

if project_root_path not in sys.path:
    sys.path.append(project_root_path)
    
from Data.Dataset_loader import load_dataset as dataset_loader

/Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Skenario
/Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection


In [3]:
path_training: str = "/Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Dataset/train"
path_testing: str = "/Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Dataset/test"

image_size = (28, 28)


# Read Image

### PILLOW

In [4]:
# img = cv2.imread("/Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Dataset/train/Rumex-obtusifolius-L_2584_jpg.rf.e6c8a0c4e80ff0f6a6d9530bfd5d4aa6.jpg")
# img = cv2.resize(img, image_size)
# plt.imshow(img)

### Image GrayScale

In [5]:

# img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# plt.imshow(img, cmap='gray')

# image = np.expand_dims(img, axis=0)
# plt.imshow(image[0], cmap='gray')

# Skenario read class dataset folder

In [6]:
def load_dataset(dataset_path, image_size=(28, 28), test_size=0.2, random_state=42):
    print(f"PATH : {dataset_path}")
    images, labels = [], []
    
    class_folder = sorted([f for f in os.listdir(dataset_path)                           
    if os.path.isdir(os.path.join(dataset_path, f))])
    print(f"Classes Found: {class_folder}")
    
    
    
    

In [7]:
load_dataset(path_training,  image_size)

PATH : /Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Dataset/train
Classes Found: ['ridderzuring', 'rumex']


In [8]:
load_dataset(path_testing, image_size)

PATH : /Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Dataset/test
Classes Found: ['ridderzuring', 'rumex']


In [9]:
x_train, y_train, labels =  dataset_loader(dataset_path=path_training, image_size=image_size)
x_test, y_test, labels = dataset_loader(dataset_path=path_testing, image_size=image_size)

Classes Found: ['ridderzuring', 'rumex']
Loading images from class: /Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Dataset/train/ridderzuring


Loading ridderzuring images: 100%|██████████| 825/825 [00:03<00:00, 211.44it/s]


Loading images from class: /Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Dataset/train/rumex


Loading rumex images: 100%|██████████| 727/727 [00:03<00:00, 213.70it/s]


Total images loaded: 1551
[[[114. 142.  83. ...  91. 112. 130.]
  [107.  98.  78. ... 104. 167. 108.]
  [ 61.  74. 137. ... 114. 104.  98.]
  ...
  [ 54. 106.  69. ...  79. 117.  92.]
  [ 88. 103. 112. ... 113. 117. 123.]
  [122.  85. 107. ... 116.  79. 118.]]

 [[ 97.  76. 139. ...  66. 127.  52.]
  [ 61.  89. 111. ...  70.  71.  55.]
  [125.  67. 105. ...  86.  89.  89.]
  ...
  [ 90.  91.  67. ... 103. 124. 113.]
  [100. 113.  87. ... 120. 121.  72.]
  [ 90. 109. 120. ... 101. 105.  84.]]

 [[ 79.  87. 114. ... 133.  72.  64.]
  [119.  85. 120. ...  89.  88. 114.]
  [124.  69.  92. ...  99. 104. 144.]
  ...
  [113.  74. 123. ... 162.  72.  99.]
  [104.  98.  90. ...  62.  64. 101.]
  [122. 128. 104. ...  90. 123.  68.]]

 ...

 [[113. 117.  69. ...  82. 131. 121.]
  [119. 108.  98. ... 128. 155. 120.]
  [ 95.  76.  89. ... 105. 101. 126.]
  ...
  [139.  53. 105. ... 107. 121. 143.]
  [134.  66. 112. ...  88. 129. 113.]
  [127. 102. 110. ...  78. 165. 175.]]

 [[ 91. 125. 117. ... 10

Loading ridderzuring images: 100%|██████████| 245/245 [00:01<00:00, 212.00it/s]


Loading images from class: /Users/ghoziwaridi/PEMOGRAMAN/Python/Deep_learning/CNN/Weed_detection/Dataset/test/rumex


Loading rumex images: 100%|██████████| 110/110 [00:00<00:00, 193.48it/s]

Total images loaded: 355
[[[106.  76. 129. ...  80.  95.  61.]
  [ 99. 111. 117. ...  77. 118. 102.]
  [106. 113.  55. ...  85.  54.  51.]
  ...
  [ 66. 101. 109. ...  42. 125.  51.]
  [ 88. 107.  90. ...  71.  77.  40.]
  [101. 134. 105. ...  49. 175. 114.]]

 [[103. 113. 139. ...  92.  67. 105.]
  [135. 100. 127. ... 104. 128. 117.]
  [113.  61. 126. ...  72.  43. 123.]
  ...
  [119.  94. 117. ...  82. 123.  97.]
  [136. 121.  95. ...  69. 126. 132.]
  [ 89. 134. 106. ...  93. 110. 168.]]

 [[113. 106.  68. ...  90.  83.  69.]
  [ 79.  95.  75. ...  51.  72.  59.]
  [ 79.  77.  83. ...  91. 103.  84.]
  ...
  [101.  83. 125. ... 105. 126. 120.]
  [122.  86. 103. ... 113. 119.  57.]
  [ 95.  61. 104. ... 118.  65.  49.]]

 ...

 [[101. 119.  86. ...  97.  55. 108.]
  [144. 115. 120. ...  94.  50. 125.]
  [110.  51.  98. ... 140.  93. 127.]
  ...
  [ 89.  82. 109. ... 116.  85. 128.]
  [ 81. 103. 112. ... 143. 133.  91.]
  [138. 110.  93. ... 102.  91.  55.]]

 [[ 75.  78.  75. ... 108